version: '3.9'

services:
  db:
    image: postgres:16
    container_name: fastapi_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9089
      POSTGRES_DB: baza_testowa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # trwa≈Çe przechowywanie danych

  fastapi:
    build: ./FasAPI
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:9089@db:5432/baza_testowa

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adam/pgdata
