services:
  db:
    image: postgres:16
    container_name: fastapi_postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 9089
      POSTGRES_DB: baza_testowa
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data   # trwa≈Çe przechowywanie danych

  fastapi:
    build: ./FastAPI/FastAPI
    container_name: fastapi_app
    ports:
      - "8005:8005"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:9089@db:5432/baza_testowa
  
  frontend:
    build: ./frontend
    container_name: punkty_strona
    ports:
      - "8081:80"
    depends_on:
      - db
      - fastapi
    volumes:
      - ./frontend/:/usr/share/nginx/html
    environment:
      - NGINX_HOST=localhost

volumes:
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/adam/pgdata
