version: '3.9'

services:
  backend:
    build: ./backend/
    container_name: fast_app
    ports:
      - '8081:8081'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://adam:9089@db:5432/mydb
  db:
    image: postgres:16
    container_name: fastapi_db
    environment:
      POSTGRES_USER: adam
      POSTGRES_PASSWORD: '9089'
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  frontend:
    build: ./frontend
    container_name: frontend_app
    ports:
      - '8080:80'

volumes:
  db_data: